title: Coding recipes
author: Anders Kaestner
email: anders.kaestner@psi.ch
description: "In this blog I am posting ideas and recipes that I hope are useful for others as well."

# social links
github_username:  anderskaestner # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
