title: Coding recipes
author: Anders Kaestner
email: anders.kaestner@psi.ch
description: > # this means to ignore newlines until "baseurl:"
In this blog I'm posting ideas and recipes that I hope are useful for others as well. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  anderskaestner # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
